
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BinhLuan
{

        [DisplayName("Mã bình luận")]
        public int MaBL { get; set; }
        [DisplayName("Mã Sản Phẩm")]
        public string MaSP { get; set; }
        [DisplayName("Mã khách hàng")]
        public string MaKH { get; set; }
        [DisplayName("Nội dung")]
        [Required(ErrorMessage = "Hãy nhập nội dung bình luận")]
        public string NoiDung { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày Đăng")]
        public Nullable<System.DateTime> NgayDang { get; set; }
        [DisplayName("Họ và tên")]
        [Required(ErrorMessage = "Hãy nhập Họ tên")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "Hãy nhập Email")]
        public string Email { get; set; }
        [DisplayName("Đã trả lời")]
        public string DaTraLoi { get; set; }

        public Nullable<int> Parent { get; set; }




        public virtual AspNetUser AspNetUser { get; set; }

    public virtual SanPham SanPham { get; set; }

}

}
