
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ChiTietDonHang
{

    [DisplayName("Mã đơn hàng")]
    public string MaDH { get; set; }

    public string MaSP { get; set; }
    [DisplayName("Số Lượng")]
    public Nullable<int> SoLuong { get; set; }
    [DisplayName("Thành tiền")]
    public Nullable<decimal> ThanhTien { get; set; }







    public virtual DonHangKH DonHangKH { get; set; }

    public virtual SanPham SanPham { get; set; }

}

}
