
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DonHangKH
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DonHangKH()
    {

        this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();

    }


        [DisplayName("Mã đơn hàng")]
        public string MaDH { get; set; }
        [DisplayName("Mã khách hàng")]
        public string MaKH { get; set; }
        [DisplayName("Phí vận chuyển")]
        public Nullable<decimal> PhiVanChuyen { get; set; }

        public string PTGiaoDich { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày đặt mua")]
        public Nullable<System.DateTime> NgayDatMua { get; set; }
        [DisplayName("Tình trạng đơn hàng")]
        public Nullable<int> TinhTrangDH { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<double> Tongtien { get; set; }
        [DisplayName("Ghi chú")]
        public string Ghichu { get; set; }
        [DisplayName("Địa chỉ")]
        public string Diachi { get; set; }
        [DisplayName("Điện thoại")]
        public string Dienthoai { get; set; }



        public virtual AspNetUser AspNetUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

}

}
