
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HangSanXuat
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HangSanXuat()
    {

        this.SanPhams = new HashSet<SanPham>();

    }


        [DisplayName("Mã Sản Phẩm")]
        public string HangSX { get; set; }
        [DisplayName("Tên Hãng")]
        [Required(ErrorMessage = "Hãy nhập tên hãng sản xuất")]
        public string TenHang { get; set; }
        [DisplayName("Trụ Sở Chính")]
        public string TruSoChinh { get; set; }
        [DisplayName("Quốc Gia")]
        public string QuocGia { get; set; }




        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SanPham> SanPhams { get; set; }

}

}
