
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class KhuyenMai
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KhuyenMai()
    {

        this.SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();

    }


        [DisplayName("Mã khuyễn mãi")]
        public string MaKM { get; set; }
        [DisplayName("Ngày bắt đầu")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        [DisplayName("Ngày kết thúc")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        [DisplayName("Nội dung")]
        public string NoiDung { get; set; }
        [DisplayName("Tên chương trình")]
        public string TenCT { get; set; }
        [DisplayName("Ảnh chương trình")]
        public string AnhCT { get; set; }





        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }

}

}
