
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SanPham
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanPham()
    {

        this.BinhLuans = new HashSet<BinhLuan>();

        this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();

        this.SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();

        this.DanhGiaSPs = new HashSet<DanhGiaSP>();

    }


        [DisplayName("Mã Sản Phẩm")]
        public string MaSP { get; set; }
        [DisplayName("Tên Sản Phẩm")]
        [Required(ErrorMessage = "Hãy nhập tên sản phẩm")]
        public string TenSP { get; set; }
        [DisplayName("Loại Sản Phẩm")]
        [Required(ErrorMessage = "Hãy chọn loại sản phẩm")]
        public string LoaiSP { get; set; }
        [DisplayName("Số lượt xem")]
        public Nullable<int> SoLuotXemSP { get; set; }
        [DisplayName("Hãng sản xuất")]
        [Required(ErrorMessage = "Hãy chọn hãng sản xuất")]
        public string HangSX { get; set; }
        [DisplayName("Xuất xứ")]
        public string XuatXu { get; set; }
        [Required(ErrorMessage = "Hãy nhập giá gốc")]
        [DisplayName("Giá gốc")]
        public Nullable<decimal> GiaGoc { get; set; }
        [DisplayName("Giá tiền")]
        public Nullable<decimal> GiaTien { get; set; }
        [AllowHtml]
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        [DisplayName("Ảnh đại diện")]
        //[Required(ErrorMessage = "Hãy chọn ảnh đại diện ")]
        public string AnhDaiDien { get; set; }
        [DisplayName("Ảnh nền")]
        public string AnhNen { get; set; }
        [DisplayName("Ảnh khác")]
        public string AnhKhac { get; set; }
        [Required(ErrorMessage = "Hãy nhập số lượng")]
        [DisplayName("Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [DisplayName("Set SP mới")]
        public Nullable<bool> isnew { get; set; }
        [DisplayName("Set SP hot")]
        public Nullable<bool> ishot { get; set; }
        [AllowHtml]
        [DisplayName("Giới thiệu")]
        public string GioiThieu { get; set; }
        [AllowHtml]
        [DisplayName("Thông số kỹ thuật")]
        public string ThongSoKyThuat { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BinhLuan> BinhLuans { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

    public virtual HangSanXuat HangSanXuat { get; set; }

    public virtual LoaiSP LoaiSP1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DanhGiaSP> DanhGiaSPs { get; set; }

}

}
