
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class TinTuc
{
    [DisplayName("Mã Tin Tức")]
    public int MaTT { get; set; }
    [Required(ErrorMessage="Hãy nhập tên chủ đề")]
    [DisplayName("Chủ đề")]
    public string ChuDe { get; set; }
    [Required(ErrorMessage="Hãy nhập tên tiêu đề")]
    [DisplayName("Tiêu đề")]
    public string TieuDe { get; set; }

    public Nullable<System.DateTime> NgayDang { get; set; }
    [Required(ErrorMessage="Hãy nhập mô tả")]
    [DisplayName("Mô tả")]
    public string MoTa { get; set; }
    [Required(ErrorMessage="Hãy chọn ảnh đại diện cho tin tức")]
    [DisplayName("Ảnh đại diện")]
    public string AnhDaiDien { get; set; }
    [Required(ErrorMessage="Hãy nhập nội dung")]
    [DisplayName("Nội dung")]
    [AllowHtml]
    public string NoiDung { get; set; }

}

}
