
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TuanStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TinTuc
{

    public int MaTT { get; set; }

    public string ChuDe { get; set; }

    public string TieuDe { get; set; }

    public Nullable<System.DateTime> NgayDang { get; set; }

    public string MoTa { get; set; }

    public string AnhDaiDien { get; set; }

    public string NoiDung { get; set; }

}

}
